baseURL = "http://127.0.0.1:8408/"
languageCode = "zh-cn"
title = "fixit 演示站"
theme = "fixit"
paginate = 5
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
description = "Flint 演示站点（fixit 主题）"
Author.name = "演示作者"
Author.link = "http://127.0.0.1:PORT/"
home.profile.enable = true

[menus]
[[menus.main]]
name = "首页"
url = "/"
weight = 1
[[menus.main]]
name = "归档"
url = "/posts/"
weight = 2
[[menus.main]]
name = "关于"
url = "/about/"
weight = 3
