baseURL = "http://127.0.0.1:8411/"
languageCode = "zh-cn"
title = "hugo-coder 演示站"
theme = "hugo-coder"
paginate = 5
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
description = "Flint 演示站点（hugo-coder 主题）"
author = "演示作者"

[menus]
[[menus.main]]
name = "首页"
url = "/"
weight = 1
[[menus.main]]
name = "归档"
url = "/posts/"
weight = 2
[[menus.main]]
name = "关于"
url = "/about/"
weight = 3
