baseURL = "http://127.0.0.1:8403/"
languageCode = "zh-cn"
title = "blog-awesome 演示站"
theme = "blog-awesome"
paginate = 5
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
description = "Flint 演示站点（blog-awesome 主题）"
Author.name = "演示作者"
Author.avatar = "icons/android-chrome-192x192.png"

[menus]
[[menus.main]]
name = "首页"
url = "/"
weight = 1
[[menus.main]]
name = "归档"
url = "/posts/"
weight = 2
[[menus.main]]
name = "关于"
url = "/about/"
weight = 3
