baseURL = "http://127.0.0.1:8404/"
languageCode = "zh-cn"
title = "blowfish 演示站"
theme = "blowfish"
paginate = 5
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
description = "Flint 演示站点（blowfish 主题）"
Author.name = "演示作者"
Author.email = "demo@example.com"
[params.homepage]
showRecent = true
showRecentItems = 5

[menus]
[[menus.main]]
name = "首页"
url = "/"
weight = 1
[[menus.main]]
name = "归档"
url = "/posts/"
weight = 2
[[menus.main]]
name = "关于"
url = "/about/"
weight = 3
