baseURL = "http://127.0.0.1:8417/"
languageCode = "zh-cn"
title = "papermod 演示站"
theme = "papermod"
paginate = 5
enableRobotsTXT = true

[pagination]
pagerSize = 5

[params]
description = "Flint 演示站点（papermod 主题）"
author = "演示作者"
homeInfoParams.Title = "演示站点"
homeInfoParams.Content = "Flint 多主题演示"

[menus]
[[menus.main]]
name = "首页"
url = "/"
weight = 1
[[menus.main]]
name = "归档"
url = "/posts/"
weight = 2
[[menus.main]]
name = "关于"
url = "/about/"
weight = 3
